---
- name: Setup Minecraft Server on AWS EC2
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    minecraft_dir: /opt/minecraft
    minecraft_jar_url: "https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar"
    minecraft_jar_path: "/opt/minecraft/server.jar"
    java_path: /usr/bin/java

  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Java 22 (Amazon Corretto)
      yum:
        name: java-22-amazon-corretto
        state: present

    - name: Create Minecraft directory
      file:
        path: "{{ minecraft_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download Minecraft Server JAR
      get_url:
        url: "{{ minecraft_jar_url }}"
        dest: "{{ minecraft_jar_path }}"
        mode: '0755'

    - name: Accept EULA
      copy:
        content: "eula=true\n"
        dest: "{{ minecraft_dir }}/eula.txt"
        owner: root
        group: root
        mode: '0644'

    - name: Create Minecraft system user
      user:
        name: minecraft
        system: yes
        create_home: no
        shell: /sbin/nologin

    - name: Set permissions on Minecraft directory
      file:
        path: "{{ minecraft_dir }}"
        state: directory
        owner: minecraft
        group: minecraft
        recurse: yes

    - name: Create systemd service for Minecraft
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory={{ minecraft_dir }}
          ExecStart={{ java_path }} -Xmx1024M -Xms1024M -jar {{ minecraft_jar_path }} nogui
          Restart=on-failure
          SuccessExitStatus=143

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and start Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started

    - name: Check Java version
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Show Java version
      debug:
        var: java_version.stdout_lines
